# Generated by Django 4.2.9 on 2024-03-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userprofile'),
        ),
    ]
